# coding: utf-8

"""
    Argo Server API

    You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`  # noqa: E501

    The version of the OpenAPI document: v3.0.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argo.workflows.client.configuration import Configuration


class IoArgoprojEventsV1alpha1Template(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'container': 'V1Container',
        'image_pull_secrets': 'list[V1LocalObjectReference]',
        'metadata': 'IoArgoprojEventsV1alpha1Metadata',
        'node_selector': 'dict(str, str)',
        'security_context': 'V1PodSecurityContext',
        'service_account_name': 'str',
        'tolerations': 'list[V1Toleration]',
        'volumes': 'list[V1Volume]'
    }

    attribute_map = {
        'container': 'container',
        'image_pull_secrets': 'imagePullSecrets',
        'metadata': 'metadata',
        'node_selector': 'nodeSelector',
        'security_context': 'securityContext',
        'service_account_name': 'serviceAccountName',
        'tolerations': 'tolerations',
        'volumes': 'volumes'
    }

    def __init__(self, container=None, image_pull_secrets=None, metadata=None, node_selector=None, security_context=None, service_account_name=None, tolerations=None, volumes=None, local_vars_configuration=None):  # noqa: E501
        """IoArgoprojEventsV1alpha1Template - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._container = None
        self._image_pull_secrets = None
        self._metadata = None
        self._node_selector = None
        self._security_context = None
        self._service_account_name = None
        self._tolerations = None
        self._volumes = None
        self.discriminator = None

        if container is not None:
            self.container = container
        if image_pull_secrets is not None:
            self.image_pull_secrets = image_pull_secrets
        if metadata is not None:
            self.metadata = metadata
        if node_selector is not None:
            self.node_selector = node_selector
        if security_context is not None:
            self.security_context = security_context
        if service_account_name is not None:
            self.service_account_name = service_account_name
        if tolerations is not None:
            self.tolerations = tolerations
        if volumes is not None:
            self.volumes = volumes

    @property
    def container(self):
        """Gets the container of this IoArgoprojEventsV1alpha1Template.  # noqa: E501


        :return: The container of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :rtype: V1Container
        """
        return self._container

    @container.setter
    def container(self, container):
        """Sets the container of this IoArgoprojEventsV1alpha1Template.


        :param container: The container of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :type: V1Container
        """

        self._container = container

    @property
    def image_pull_secrets(self):
        """Gets the image_pull_secrets of this IoArgoprojEventsV1alpha1Template.  # noqa: E501


        :return: The image_pull_secrets of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :rtype: list[V1LocalObjectReference]
        """
        return self._image_pull_secrets

    @image_pull_secrets.setter
    def image_pull_secrets(self, image_pull_secrets):
        """Sets the image_pull_secrets of this IoArgoprojEventsV1alpha1Template.


        :param image_pull_secrets: The image_pull_secrets of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :type: list[V1LocalObjectReference]
        """

        self._image_pull_secrets = image_pull_secrets

    @property
    def metadata(self):
        """Gets the metadata of this IoArgoprojEventsV1alpha1Template.  # noqa: E501


        :return: The metadata of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :rtype: IoArgoprojEventsV1alpha1Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this IoArgoprojEventsV1alpha1Template.


        :param metadata: The metadata of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :type: IoArgoprojEventsV1alpha1Metadata
        """

        self._metadata = metadata

    @property
    def node_selector(self):
        """Gets the node_selector of this IoArgoprojEventsV1alpha1Template.  # noqa: E501


        :return: The node_selector of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._node_selector

    @node_selector.setter
    def node_selector(self, node_selector):
        """Sets the node_selector of this IoArgoprojEventsV1alpha1Template.


        :param node_selector: The node_selector of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :type: dict(str, str)
        """

        self._node_selector = node_selector

    @property
    def security_context(self):
        """Gets the security_context of this IoArgoprojEventsV1alpha1Template.  # noqa: E501


        :return: The security_context of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :rtype: V1PodSecurityContext
        """
        return self._security_context

    @security_context.setter
    def security_context(self, security_context):
        """Sets the security_context of this IoArgoprojEventsV1alpha1Template.


        :param security_context: The security_context of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :type: V1PodSecurityContext
        """

        self._security_context = security_context

    @property
    def service_account_name(self):
        """Gets the service_account_name of this IoArgoprojEventsV1alpha1Template.  # noqa: E501


        :return: The service_account_name of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :rtype: str
        """
        return self._service_account_name

    @service_account_name.setter
    def service_account_name(self, service_account_name):
        """Sets the service_account_name of this IoArgoprojEventsV1alpha1Template.


        :param service_account_name: The service_account_name of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :type: str
        """

        self._service_account_name = service_account_name

    @property
    def tolerations(self):
        """Gets the tolerations of this IoArgoprojEventsV1alpha1Template.  # noqa: E501


        :return: The tolerations of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :rtype: list[V1Toleration]
        """
        return self._tolerations

    @tolerations.setter
    def tolerations(self, tolerations):
        """Sets the tolerations of this IoArgoprojEventsV1alpha1Template.


        :param tolerations: The tolerations of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :type: list[V1Toleration]
        """

        self._tolerations = tolerations

    @property
    def volumes(self):
        """Gets the volumes of this IoArgoprojEventsV1alpha1Template.  # noqa: E501


        :return: The volumes of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :rtype: list[V1Volume]
        """
        return self._volumes

    @volumes.setter
    def volumes(self, volumes):
        """Sets the volumes of this IoArgoprojEventsV1alpha1Template.


        :param volumes: The volumes of this IoArgoprojEventsV1alpha1Template.  # noqa: E501
        :type: list[V1Volume]
        """

        self._volumes = volumes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojEventsV1alpha1Template):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojEventsV1alpha1Template):
            return True

        return self.to_dict() != other.to_dict()
